config/routes.rb
Rails.application.routes.draw do
  
  resources :conversations
  get 'home/help'
  use_doorkeeper
  resources :episodes do 
    resources :exercises
      get '/exercise_preview', to: 'exercises#preview'
  end

  get '/episodes_preview', to: 'episodes#preview'
  
  

  resources :choices
  resources :questions do 
    resources :choices
  end

  resources :exercises do 
    get 'up', on: :member
    get 'down', on: :member
    resources :steps 
  end  
  
  resources :steps do
    get 'up', on: :member
    get 'down', on: :member 
    resources :questions
  end
    
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  


  get 'home/index'
  get 'home/help'
  get 'home/privacy'

  resources :users do
      collection do
        get 'group_auth'
        get 'group_assign_counselor'
      end
    
    get 'promoteToCounselor', on: :member
    get 'promoteToNormal', on: :member
    resources :timelines do 
      resources :exercise_histories
    end 
  end
  
  get '/users_auth', to: 'users#auth'
  get '/assign_counselor', to: 'users#assign_counselor'




  resources :timelines
  resources :feedbacks
  resources :conversations
  
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # use_doorkeeper
  mount API::Base => '/'
  mount GrapeSwaggerRails::Engine =>  '/swagger_doc'
  
  root to: "users#index"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, 
         :trackable

  enum user_type: [:normal, :counselor, :admin]
  enum gender: [:male, :female]

  
  has_many :day_histories, dependent: :destroy
  has_many :answer, dependent: :destroy
  has_many :mind_trackings, -> { order(rdate: :asc) }, dependent: :destroy
  has_many :timelines, -> { order(no: :desc) }, dependent: :destroy
  
  def age
    Time.new.year - self.birth_year
  end
end

app/controllers/api/v1/users.rb
module API
  module V1
    class Users < Grape::API
    
      include API::V1::Defaults
    
      

      resource :users do
        desc 'user info for certain email'
        params do
          requires :email, type: String, desc: 'User Email'
        end
        get 'find' do
          user = User.where(email: params[:email])
        end

        desc 'get current user info'
        oauth2
        get 'me' do
          current_user
        end

        oauth2
        desc 'Update User Info'
        params do
          optional :name, type: String, desc: 'name of user'
          optional :nickname, type: String, desc: "nickname of user"
          optional :student_no, type: String, desc: "student_no of user"
          optional :birth_year, type: Integer, desc: "birth_year of user"
        end 
        put '/:id' do
          User.find_by_id(params[:id]).update({name:params[:name]})
          User.find_by_id(params[:id]).update({nickname:params[:nickname]})
          User.find_by_id(params[:id]).update({student_no:params[:student_no]})
          User.find_by_id(params[:id]).update({birth_year:params[:birth_year]})
          User.find_by_id(params[:id])
        end

      
        

        paginate per_page: 30, max_per_page: 100, offset: 0
        oauth2
        get '/' do
          users = User.all
          paginate(users)
        end
      end

      rescue_from ActiveRecord::RecordInvalid do |error|
        error!({code: 101, details: error.record.errors.details}, 400)
      end
    end
  end
end

app/controllers/concerns/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user

  # GET /episodes
  # GET /episodes.json
  def index
    @user = User.all
  end

  # GET /episodes/1
  # GET /episodes/1.json
  def show
  end

  # GET /episodes/new
  def new
    @user = User.new
  end

  # GET /episodes/1/edit
  def edit
  end

  # POST /episodes
  # POST /episodes.json
  def create
  

    respond_to do |format|
      if @episode.save
        format.html { redirect_to @episode, notice: 'Episode was successfully created.' }
        format.json { render :show, status: :created, location: @episode }
      else
        format.html { render :new }
        format.json { render json: @episode.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /episodes/1
  # PATCH/PUT /episodes/1.json
  

  # DELETE /episodes/1
  # DELETE /episodes/1.json


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit()
    end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :nickname, :gender, :student_no, :birth_year])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  def new
    super
  end

  # POST /resource/sign_in
  def create
    super
  end

  # DELETE /resource/sign_out
  def destroy
    super
  end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_in_params
    devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :promoteToCounselor, :promoteToNormal, :down, :destroy]
  # before_action :set_breadcrumb
  # GET /users
  # GET /users.json
  def index
    if params[:user_type].present?
      @users = User.where(:user_type => params[:user_type]).order(user_type: :desc).order(name: :asc).page(params[:page]).per(10)
    else
      @users = User.where('user_type != 2').order(user_type: :desc).order(name: :asc).page(params[:page]).per(10)
    end
    
    @ex_histo_exist = ExerciseHistory.where(:user => @user).where('end_at is not null')
    @my_users = User.where(:counselor_id => current_user.id).order(name: :asc).page params[:page]
    @timeline = Timeline.where(:user => @user).where(:timeline_type => "day_history").last
    @user_type = params[:user_type]
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @clients = User.where(:counselor_id => @user.id)
  end

  # GET /users/new
  def new
    @user = @exercise.users.new
  end

  # GET /users/1/edit
  def edit
    add_breadcrumb "Edit"
  end

  # POST /users
  # POST /users.json
  def create
    @user = @exercise.users.new(user_params)
    @user.no = (@exercise.users.maximum('no') || 0) + 1

    respond_to do |format|
      if @user.save
        format.html { redirect_to exercise_users_path(@exercise), notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    # @exercise = @users.exercise
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to users_path, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def promoteToCounselor
    if @user.user_type == "normal"
      User.transaction do 
        @user.user_type = 1
        @user.save
      end
    end
    redirect_to users_path
  end

  def promoteToNormal
    if @user.user_type == "counselor"
      User.transaction do 
        @user.user_type = 0
        @user.save
      end
    end
    redirect_to users_path
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_path, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def auth
    @users = User.where("user_type = 0").order(name: :asc).page(params[:page]).per(10)
  end 

  def assign_counselor
    @users = User.where("user_type = 0").order(name: :asc).page(params[:page]).per(10)
    @counselors = User.where("user_type = 1")
  end

  def group_assign_counselor
    @user_ids_str = params[:hidden]
    @counselor_id = params[:counselor_id]
    if @user_ids_str.present?
      for user_id in @user_ids_str.split(",")
        @user = User.find(user_id)
        @user.counselor_id = @counselor_id
        @user.save
      end
    end
    redirect_to users_path
  end

  def group_auth
    @user_ids_str = params[:hidden]
    if @user_ids_str.present?
      for user_id in @user_ids_str.split(",")
        @user = User.find(user_id)
        @user.user_type = 1
        @user.save
      end
    end
    redirect_to users_path
  end




  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    def set_exercise
      @exercise = Exercise.find(params[:exercise_id])
    end  

    # def set_breadcrumb
    #   add_breadcrumb "Users", users_path
    # end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:no, :user_type, :counselor_id, :name, :nickname, :student_no, :birth_year)
    end
end

app/views/users/assign_counselor.erb
<div class="page-header">
  <h1 class="font-weight-bold">상담사 배정</h1>
</div>
<hr class="headerUnderline">
<div class="table-responsive">
  <%= form_tag group_assign_counselor_users_path, method: :get do %>
    <div class="row">
      <div class="col-2">
        <h5>배정 받을 상담사</h5>
      </div>
      <div class="col-2">
        <select id="counselor_id" class="custom-select custom-select-md mb-3" name="counselor_id">
          <%= options_from_collection_for_select(User.where(:user_type => "counselor"), :id, :name) %>
        </select>
      </div>
    </div>
    
    <table class="table table table-hover">
      <thead class="bg-light">
        <tr class="text-center header">
          <th>이름</th>
          <th>이메일</th>
          <th>성별</th>
          <th>출생연도</th>
          <th>사용자 종류</th>
          <th>선택</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% if current_user.user_type == "admin"%>
          <% @users.each do |user| %>
            <tr id=<%= user.id %>>
              <td class="text-center"><%= user.name %></td>
              <td class="text-center"><%= user.email %></td>
              <td class="text-center"><%= I18n.t("gender.#{user.gender}") %></td>
              <td class="text-center"><%= user.birth_year %></td>
              <% if user.user_type == "counselor"%>
                <td >
                  <div class="orangeBadge">
                    <%= I18n.t("user_type.#{user.user_type}") %>
                  </div>
                </td>
              <% else %>
                <td>
                  <div class="greenBadge">
                    <%= I18n.t("user_type.#{user.user_type}") %>
                  </div>
                </td> 
              <% end %> 
              <td>
                <input id=<%= user.id %> class="authCheckbox" type="checkbox" name="user_ids[]" value=<%= user.id %> />
              </td> 
              <td>
            </tr>
          <% end %> 
          <input id="hidden" name="hidden", hidden>
        <% end %>
      </tbody>
    </table>
  <%= paginate @users, theme: 'twitter-bootstrap-4' %>
</div>

<hr class="footerLine">
</div>
<div class="footer"> 
    <div>
      <%= link_to users_path, class: 'btn btn-outline-dark' do %>
        <span> 사용자 목록</span>
      <% end %>
    </div>
      <%= submit_tag "상담사 배정", :class => 'btn btn-primary' %>
    <% end%>
  </div>
</div>
<script>
  $(function() {
    $( document ).ready(function() {
      let values = [];  
      if (localStorage.getItem('prev') != null) {
        let previousSel = JSON.parse("["+ localStorage.getItem('prev') + "]");
        let values = previousSel;  
        previousSel.forEach(e => {
          $(`:checkbox[value=${e}]`).prop("checked","true");
        })
        $('#hidden').val(previousSel);
      }

      if (localStorage.getItem('selectedCounselor') != null) {
        $('#counselor_id').val( localStorage.getItem('selectedCounselor') );
      }
    });

    $('input[name="user_ids[]"]').change(function() {
      let values = [];
      if (localStorage.getItem('prev') != null) {
        let previousSel = JSON.parse("["+ localStorage.getItem('prev') + "]");
        values = previousSel;  
      }
      let prev = localStorage.getItem('prev');

      $.each($('input[name="user_ids[]"]:checked'), function(){
        if ( !values.includes(Number($(this).val()))) {
          values.push(Number($(this).val()))
        }
      });
      $.each($('input[name="user_ids[]"]:not(:checked)'), function(){
        if ( values.includes(Number($(this).val()))) {
          values = values.filter(item => item !== Number($(this).val()))
        }
      });

      $('#hidden').val(values);
      localStorage.setItem("hidden", values);
    });

    $( ".page-link" ).click(function() {
      $('#hidden').val(localStorage.setItem('prev', $('#hidden').val()));
      $('#counselor_id').val(localStorage.setItem('selectedCounselor', $('#counselor_id').val()));
    });

    $("form").on("submit", function() {
      localStorage.clear();
    });

    $(window).on('hashchange', function(event) {
      localStorage.clear();
    });

  });
</script>

app/views/users/auth.html.erb
<div class="page-header">
  <h1 class="font-weight-bold ">상담사 권한 부여</h1>
</div>
<hr class="headerUnderline">
<div class="table-responsive">
  <%= form_tag group_auth_users_path, method: :get do %>
    <table class="table table table-hover">
      <thead class="bg-light">
        <tr class="text-center header">
          <th>이름</th>
          <th>이메일</th>
          <th>성별</th>
          <th>출생연도</th>
          <th>사용자 종류</th>
          <th>선택</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% if current_user.user_type == "admin"%>
          <% @users.each do |user| %>
            <tr id=<%= user.id %>>
              <td class="text-center"><%= user.name %></td>
              <td class="text-center"><%= user.email %></td>
              <td class="text-center"><%= I18n.t("gender.#{user.gender}") %></td>
              <td class="text-center"><%= user.birth_year %></td>
              <% if user.user_type == "counselor"%>
                <td >
                  <div class="orangeBadge">
                    <%= I18n.t("user_type.#{user.user_type}") %>
                  </div>
                </td>
              <% else %>
                <td>
                  <div class="greenBadge">
                    <%= I18n.t("user_type.#{user.user_type}") %>
                  </div>
                </td> 
              <% end %> 
              <td>
                <input id=<%= user.id %> class="authCheckbox" type="checkbox" name="user_ids[]" value=<%= user.id %> />
              </td> 
              <td>
            </tr>
          <% end %> 
          <input id="hidden" name="hidden", hidden>
        <% end %>
      </tbody>
    </table>
  <%= paginate @users, theme: 'twitter-bootstrap-4' %>
</div>

<hr class="footerLine">
</div>
<div class="footer"> 
    <div>
      <%= link_to users_path, class: 'btn btn-outline-dark' do %>
        <span> 사용자 목록</span>
      <% end %>
    </div>
      <%= submit_tag "상담사 권한부여", :class => 'btn btn-primary' %>
    <% end%>
  </div>
</div>
<script>
  $(function() {
    $( document ).ready(function() {
      let values = [];  
      if (localStorage.getItem('prev') != null) {
        let previousSel = JSON.parse("["+ localStorage.getItem('prev') + "]");
        let values = previousSel;  
        previousSel.forEach(e => {
          $(`:checkbox[value=${e}]`).prop("checked","true");
        })
        $('#hidden').val(previousSel);
      }});

    $('input[name="user_ids[]"]').change(function() {
      let values = [];
      if (localStorage.getItem('prev') != null) {
        let previousSel = JSON.parse("["+ localStorage.getItem('prev') + "]");
        values = previousSel;  
      }
      let prev = localStorage.getItem('prev');

      $.each($('input[name="user_ids[]"]:checked'), function(){
        if ( !values.includes(Number($(this).val()))) {
          values.push(Number($(this).val()))
        }
      });
      $.each($('input[name="user_ids[]"]:not(:checked)'), function(){
        if ( values.includes(Number($(this).val()))) {
          values = values.filter(item => item !== Number($(this).val()))
        }
      });

      $('#hidden').val(values);
      localStorage.setItem("hidden", values);
    });

    $( ".page-link" ).click(function() {
      $('#hidden').val(localStorage.setItem('prev', $('#hidden').val()));
    });

    $("form").on("submit", function() {
      localStorage.clear();
    });

    $(window).on('hashchange', function(event) {
      localStorage.clear();
    });

  });
</script>

app/views/users/edit.html.erb
<div class="page-header">
  <% if @user.counselor_id == nil %>
    <h1 class="font-weight-bold">상담사 배정</h1>
  <% else %> 
    <h1 class="font-weight-bold">상담사 변경</h1>
  <% end %>
</div>
<hr class="headerUnderline">
 <%= form_for([@user], html: { role: "form" }) do |f| %>
  <% if @user.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h4>

      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group"></div>
    <%= f.label "배정 받을 상담사 이름" %>
    <%= f.select :counselor_id, User.where(:user_type => "counselor").collect{|p| [ p.name, p.id ]}, { include_blank: true }, class: "form-control" %>
  </div>

<hr>
<div class = "newFooter">
  <div class = "mr-2"> 
    <%= f.submit "배정 완료", class: "btn btn-primary" %>
    <% end %>
  </div>
  <div>
    <%= link_to users_path, class: 'btn btn-outline-dark' do %>
      <span class="glyphicon glyphicon-list-alt"></span>
      취소
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class="page-header">
  <h1 class="font-weight-bold ">
    <% if current_user.user_type == "admin" %>
      사용자 관리
    <%else%>
      내담자 관리
    <%end%>
  </h1>
</div>
<hr class="headerUnderline">
<% if current_user.user_type == "admin" %>
  <div id= "groupAuthButton">
    <div>
      <select class="custom-select custom-select-lg mb-3">

        <% if @user_type == '1' %>
          <option value="all">전체</option>
          <option value=0>내담자</option>
          <option value=1 selected>상담사</option>
        <% elsif @user_type == '0'  %>
          <option value="all">전체</option>
          <option value=0 selected>내담자</option>
          <option value=1>상담사</option>
        <% else %>
          <option value="all">전체</option>
          <option value=0>내담자</option>
          <option value=1>상담사</option>
        <% end %>
      </select>
    </div>
    <div>
      <%= link_to assign_counselor_path, class: 'btn btn-secondary mr-2' do %>
        <span>상담사 배정</span>
      <% end %>
      <%= link_to users_auth_path, class: 'btn btn-primary' do %>
        <span>상담사 권한 부여</span>
      <% end %>
    </div>
  </div>
<% end %>

<div class="table-responsive">
  <table class="table table table-hover">
    <thead class="bg-light text-center">
      <th>이름</th>
      <th>닉네임</th>
      <th>성별</th>
      <th>출생년도</th>
      <th>학번</th>
      <th>사용자 종류</th>
      <% if @user_type != '1' %>
        <th>신호등</th>
      <% end %>
      <th></th>
    </thead>
    <tbody>
      <% if current_user.user_type == "admin"%>
        <% @users.each do |user| %>
        <% if user.user_type == "normal"%>
          <tr class="normal" onclick="location.href='<%= user_timelines_path(user) %>'">
        <% else %>
          <tr class="counselor" onclick="location.href='<%=user_path(user) %>'">
        <% end %>  
            <td class="text-center"><%= user.name %></td>
            <td class="text-center"><%= user.nickname %></td>
            <td class="text-center"><%= I18n.t("gender.#{user.gender}") %></td>
            <td class="text-center"><%= user.birth_year %></td>
            <td class="text-center"><%= user.student_no %></td>
            <% if user.user_type == "counselor"%>
              <td >
                <div class="orangeBadge">
                  <%= I18n.t("user_type.#{user.user_type}") %>
                </div>
              </td>
            <% else %>
              <td>
                <div class="greenBadge">
                  <%= I18n.t("user_type.#{user.user_type}") %>
                </div>
              </td> 
            <% end %> 
            <% if @user_type != '1' %> 
              <td>
                <% if user.user_type == "normal" && Timeline.where(:user => user).where(:timeline_type => "day_history").present? && @ex_histo_exist && ( Date.today - Timeline.where(:user => user).where(:timeline_type => "day_history").last.rdate ).to_i == 0  %>
                  <span class="greenDot"></span>
                <% elsif user.user_type == "normal" && Timeline.where(:user => user).where(:timeline_type => "day_history").present? && @ex_histo_exist && ( Date.today - Timeline.where(:user => user).where(:timeline_type => "day_history").last.rdate ).to_i == 1  %>
                  <span class="yellowDot"></span>
                <% elsif user.user_type == "normal" %>
                  <span class="redDot"></span>
                <% end %>
              </td>
            <% end %> 
            <td class="modifyButtons">
              <%if user.user_type == "normal" && user.counselor_id == nil%>
                <%= link_to '상담사 배정하기',  edit_user_path(user), class: "btn btn-secondary btn-sm mr-2" %>
              <% elsif user.user_type == "counselor" %>
                <%= link_to '내담자로 전환', promoteToNormal_user_path(user), class: "btn btn-success btn-sm mr-2", data: { confirm: "#{user.name}을 내담자로 전환하시겠습니까?" } %>    
              <% else %>
                <%= link_to '상담사 변경하기',  edit_user_path(user), class: "btn btn-info btn-sm mr-2" %>
              <% end %>
            </td>
          </tr>
        <% end %>
      <% else %>
        <% @my_users.each do |user| %>
        <tr onclick="location.href='<%= user_timelines_path(user) %>'">
            <td class="text-center"><%= user.name %></td>
            <td class="text-center"><%= user.nickname %></td>
            <td class="text-center"><%= I18n.t("gender.#{user.gender}") %></td>
            <td class="text-center"><%= user.birth_year %></td>
            <td class="text-center"><%= user.student_no %></td>
          <% if user.user_type == "counselor"%>
            <td >
              <div class="orangeBadge">
                <%= I18n.t("user_type.#{user.user_type}") %>
              </div>
            </td>
            <% else %>
              <td>
                <div class="greenBadge">
                  <%= I18n.t("user_type.#{user.user_type}") %>
                </div>
              </td> 
            <% end %>
            <td>
              <% if user.user_type == "normal" && Timeline.where(:user => user).where(:timeline_type => "day_history").present? && @ex_histo_exist && ( Date.today - Timeline.where(:user => user).where(:timeline_type => "day_history").last.rdate ).to_i == 0  %>
                <span class="greenDot"></span>
              <% elsif user.user_type == "normal" && Timeline.where(:user => user).where(:timeline_type => "day_history").present? && @ex_histo_exist && ( Date.today - Timeline.where(:user => user).where(:timeline_type => "day_history").last.rdate ).to_i == 1  %>
                <span class="yellowDot"></span>
              <% elsif user.user_type == "normal" %>
                <span class="redDot"></span>
              <% end %>
            </td>  
            <td></td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
  <div class=pagination>
    <% if current_user.user_type == "admin"%>
      <%= paginate @users, theme: 'twitter-bootstrap-4' %>
    <% else %>
      <%= paginate @my_users, theme: 'twitter-bootstrap-4' %>
    <% end %> 
  </div>
  <hr class="footerLine">
</div>
<script>
  $('select').on('change', function() {
    var url = "/users" + (this.value != "all" ? ("?user_type="+this.value) : (""))
    window.location.href = url;
  });
</script>