config/routes.rb
Rails.application.routes.draw do
  
  resources :conversations
  get 'home/help'
  use_doorkeeper
  resources :episodes do 
    resources :exercises
      get '/exercise_preview', to: 'exercises#preview'
  end

  get '/episodes_preview', to: 'episodes#preview'
  
  

  resources :choices
  resources :questions do 
    resources :choices
  end

  resources :exercises do 
    get 'up', on: :member
    get 'down', on: :member
    resources :steps 
  end  
  
  resources :steps do
    get 'up', on: :member
    get 'down', on: :member 
    resources :questions
  end
    
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  


  get 'home/index'
  get 'home/help'
  get 'home/privacy'

  resources :users do
      collection do
        get 'group_auth'
        get 'group_assign_counselor'
      end
    
    get 'promoteToCounselor', on: :member
    get 'promoteToNormal', on: :member
    resources :timelines do 
      resources :exercise_histories
    end 
  end
  
  get '/users_auth', to: 'users#auth'
  get '/assign_counselor', to: 'users#assign_counselor'




  resources :timelines
  resources :feedbacks
  resources :conversations
  
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # use_doorkeeper
  mount API::Base => '/'
  mount GrapeSwaggerRails::Engine =>  '/swagger_doc'
  
  root to: "users#index"
end

app/models/episode.rb
class Episode < ApplicationRecord
  has_many :exercises, -> { order(no: :asc)}, dependent: :destroy
end

app/controllers/api/v1/episodes.rb
module API
  module V1
    class Episodes < Grape::API
      include API::V1::Defaults

      resource :episodes do
        desc 'This is for finding all exercises that is in a certain episode'
        oauth2 
        get '/:id' do
          episode = Episode.find(params[:id])
          result = episode.exercises.map do |e| 
            eh = ExerciseHistory.where(['exercise_id = ? AND user_id = ?', e.id, current_user.id]).first
            {exercise: e, completed: eh.present?}
          end
        end  

        paginate per_page: 30, max_per_page: 100, offset: 0
        oauth2
        get '/' do

          episodes = Episode.all
          paginate(episodes)
        end
      end

      rescue_from ActiveRecord::RecordInvalid do |error|
        error!({code: 101, details: error.record.errors.details}, 400)
      end
    end
  end
end

app/controllers/episodes_controller.rb
class EpisodesController < ApplicationController
  before_action :set_episode, only: [:show, :edit, :update, :destroy]

  # GET /episodes
  # GET /episodes.json
  def index
    @episodes = Episode.all
  end

  # GET /episodes/1
  # GET /episodes/1.json
  def show
  end

  # GET /episodes/new
  def new
    @episode = Episode.new
  end

  # GET /episodes/1/edit
  def edit
    
  end

  # POST /episodes
  # POST /episodes.json
  def create
    @episode = Episode.new(episode_params)

    respond_to do |format|
      if @episode.save
        format.html { redirect_to @episode, notice: 'Episode was successfully created.' }
        format.json { render :show, status: :created, location: @episode }
      else
        format.html { render :new }
        format.json { render json: @episode.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /episodes/1
  # PATCH/PUT /episodes/1.json
  def update
    respond_to do |format|
      if @episode.update(episode_params)
        format.html { redirect_to episodes_url, notice: 'Episode was successfully updated.' }
        format.json { render :show, status: :ok, location: @episode }
      else
        format.html { render :edit }
        format.json { render json: @episode.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /episodes/1
  # DELETE /episodes/1.json
  def destroy
    @episode.destroy
    respond_to do |format|
      format.html { redirect_to episodes_url, notice: 'Episode was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def preview
    @episodes = Episode.all
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_episode
      @episode = Episode.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def episode_params
      params.require(:episode).permit(:no, :title)
    end
end

app/helpers/episodes_helper.rb
module EpisodesHelper
end

app/views/episodes/_app_image.html.erb
<div class="sample-page image-type">
  <h3>gg</h3>
  <div class="text">
    <%=h ggg %>
  </div>
</div>

app/views/episodes/_form.html.erb
<%= form_for(@episode, html: { role: "form" }) do |f| %>
  <% if @episode.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@episode.errors.count, "error") %> prohibited this episode from being saved:</h4>

      <ul>
      <% @episode.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label "제목" %>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/episodes/edit.html.erb
<div class="page-header">
  <h1>회기 수정</h1>
</div>

<%= render 'form' %>


<hr>
<%= link_to episodes_path, class: 'btn btn-default' do %>
  <span class="glyphicon glyphicon-list-alt"></span>
  Back
<% end %>
<%= link_to @episode, class: 'btn btn-default' do %>
  <span class="glyphicon glyphicon-info-sign"></span>
  Show
<% end %>

app/views/episodes/index.html.erb
<div class="page-header">
  <h1 class="font-weight-bold">마음여행 관리 - 회기 목록</h1>
</div>
<hr class="headerUnderline">

<div class="table-responsive">
  <table class="table table-sm table-hover">
    <thead>
      <tr>
        <th>순서</th>
        <th>제목</th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @episodes) do |episode| %>
        <td><%= episode.no %></td>
        <td><%=link_to episode.title, episode_exercises_path(episode) %></td>
        <td>
          <%= link_to '수정', edit_episode_path(episode) %> 
        </td>
      <% end %>
    </tbody>
  </table>
  <hr class="footerLine">
  <div id= "groupAuthButton">
  <%= link_to episodes_preview_path, class: 'btn btn-primary' do %>
    <span>회기 페이지 미리보기</span>
  <% end %>  
</div>

app/views/episodes/new.html.erb
<div class="page-header">
  <h1>New episode</h1>
</div>

<%= render 'form' %>

<%= link_to episodes_path, class: 'btn btn-default' do %>
  <span class="glyphicon glyphicon-list-alt"></span>
  Back
<% end %>

app/views/episodes/preview.html.erb
<div class="page-header">
  <h1 class="font-weight-bold">회기 페이지 미리보기</h1>
</div>
  <hr class="headerUnderline">

  <div class="sample-page image-type">
    <div id="exercises_preview_title">
      마음여행
    </div>
    <% @episodes.each do |episode| %>
        <div  id="episodes_preview_content">
        <div><%= episode.no %></div>
        <i class="fas fa-clock"></i>
        <div class="ml-4"><%=episode.title%></div>
      </div>
    <% end %>
  </div>
  <hr class="footerLine">
  <div class="footer"> 
    <div>
      <%= link_to episodes_path, class: 'btn btn-outline-dark' do %>
        <span> 회기 목록</span>
      <% end %>
  </div>
</div>

app/views/episodes/show.html.erb
<div class="page-header">
  <h1>Show episode</h1>
</div>

<dl class="dl-horizontal">
  <dt>No:</dt>
  <dd><%= @episode.no %></dd>

  <dt>Title:</dt>
  <dd><%= @episode.title %></dd>

</dl>
<%= link_to episodes_path, class: 'btn btn-default' do %>
  <span class="glyphicon glyphicon-list-alt"></span>
  Back
<% end %>
<%= link_to edit_episode_path(@episode), class: 'btn btn-primary' do %>
  <span class="glyphicon glyphicon-pencil"></span>
  Edit
<% end %>