config/routes.rb
Rails.application.routes.draw do
  
  resources :conversations
  get 'home/help'
  use_doorkeeper
  resources :episodes do 
    resources :exercises
      get '/exercise_preview', to: 'exercises#preview'
  end

  get '/episodes_preview', to: 'episodes#preview'
  
  

  resources :choices
  resources :questions do 
    resources :choices
  end

  resources :exercises do 
    get 'up', on: :member
    get 'down', on: :member
    resources :steps 
  end  
  
  resources :steps do
    get 'up', on: :member
    get 'down', on: :member 
    resources :questions
  end
    
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  


  get 'home/index'
  get 'home/help'
  get 'home/privacy'

  resources :users do
      collection do
        get 'group_auth'
        get 'group_assign_counselor'
      end
    
    get 'promoteToCounselor', on: :member
    get 'promoteToNormal', on: :member
    resources :timelines do 
      resources :exercise_histories
    end 
  end
  
  get '/users_auth', to: 'users#auth'
  get '/assign_counselor', to: 'users#assign_counselor'




  resources :timelines
  resources :feedbacks
  resources :conversations
  
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # use_doorkeeper
  mount API::Base => '/'
  mount GrapeSwaggerRails::Engine =>  '/swagger_doc'
  
  root to: "users#index"
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :exercise_history
end

app/models/choice.rb
class Choice < ApplicationRecord
  belongs_to :question
  
  def prev
    self.question.choices.where('no < ?', self.no).last
  end

  def next
    self.question.choices.where('no > ?', self.no).first
  end

  def first?
    self.prev.blank?
  end

  def last?
    self.next.blank?
  end

  def next_step
    Step.where('id = ?', self.next_step_id).first
  end

  def default_next_step
    self.question.step.next
  end

  def next_step_no
    return self.next_step.no if self.next_step.present?
    return self.default_next_step.no if self.default_next_step.present?
  end
end

app/models/conversation.rb
class Conversation < ApplicationRecord
  belongs_to :user
end

app/models/day_history.rb
class DayHistory < ApplicationRecord
  belongs_to :user
  has_many :exercise_history, dependent: :destroy 
  has_many :answers, through: :exercise_history
  has_one :timeline
end

app/models/episode.rb
class Episode < ApplicationRecord
  has_many :exercises, -> { order(no: :asc)}, dependent: :destroy
end

app/models/exercise.rb
class Exercise < ApplicationRecord
  belongs_to :episode
  has_many :steps, -> { order(no: :asc)}, dependent: :destroy
  has_many :exercise_histories, dependent: :destroy

  def prev
    Exercise.where('no < ?', self.no).last
  end

  def next
    Exercise.where("no > ?", self.no).first
  end

  def first?
    self.prev.blank?
  end

  def last?
    self.next.blank?
  end
end

app/models/exercise_history.rb
class ExerciseHistory < ApplicationRecord
  belongs_to :day_history
  belongs_to :exercise
  has_many :answers, -> { order(no: :asc)}, dependent: :destroy

  def duration
    @minute_diff = ((self.end_at - self.begin_at) / 1.minutes).to_i
    if (@minute_diff > 1)
      return ((self.end_at - self.begin_at) / 1.minutes).to_i
    else return 1
    end
  end
end

app/models/feedback.rb
class Feedback < ApplicationRecord
  belongs_to :user
  has_one :timeline, :inverse_of => :feedback
end

app/models/mind_tracking.rb
class MindTracking < ApplicationRecord
  belongs_to :user

  def rdate_str
    self.rdate.strftime("%Y-%m-%d")
  end
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :step
  has_many :choices, -> { order(no: :asc)}, dependent: :destroy
  enum question_type: [:long, :short, :choice, :measure, :record]

  def prev
    self.step.questions.where('no < ?', self.no).last
  end

  def next
    self.step.questions.where('no > ?', self.no).first
  end

  def first?
    self.prev.blank?
  end

  def last?
    self.next.blank?
  end


  def max_choices
    return 5 if self.step.choice_type?
    return 0
  end

  def choice_required?
    self.max_choices > 0
  end

  def question_registrable?
    self.choices.size < self.max_choices
  end
end

app/models/step.rb
class Step < ApplicationRecord
  belongs_to :exercise
  has_many :questions, -> { order(no: :asc)}, dependent: :destroy

  has_one_attached :audio
  has_one_attached :video
  has_one_attached :cover
  
  enum step_type: [
    :image_type, :image_full_type, :audio_type, :animation_type,
    :textbox_type, :question_type, :choice_type, :measure_type, 
    :record_type, :tombstone_type, :sandswamp_game_type, :water_tap_type, 
    :bubble_type, :pure_pain_type, :picker_type 
  ]

  def prev
    self.exercise.steps.where('no < ?', self.no).last
  end

  def next
    self.exercise.steps.where('no > ?', self.no).first
  end

  def first?
    self.prev.blank?
  end

  def last?
    self.next.blank?
  end

  def action_required?
    self.animation_type?
  end

  def video_required?
    self.animation_type?
  end

  def audio_url
    self.attach_url self.audio
  end
  
  def video_url
    self.attach_url self.video
  end

  def cover_url
    self.attach_url self.cover
  end

  def question_required?
    self.max_questions > 0
  end

  def max_questions
    return 1 if self.textbox_type? || self.choice_type? || self.record_type? || self.tombstone_type? || self.picker_type?
    return 3 if self.question_type? || self.measure_type?
    return 0
  end

  def question_registrable?
    self.questions.size < self.max_questions
  end
end

app/models/timeline.rb
class Timeline < ActiveRecord::Base
  enum timeline_type: [:day_history, :feedback]
  belongs_to :user
  belongs_to :day_history, optional: true, dependent: :destroy
  belongs_to :feedback, optional: true, :inverse_of => :timeline, dependent: :destroy
  accepts_nested_attributes_for :feedback, allow_destroy: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, 
         :trackable

  enum user_type: [:normal, :counselor, :admin]
  enum gender: [:male, :female]

  
  has_many :day_histories, dependent: :destroy
  has_many :answer, dependent: :destroy
  has_many :mind_trackings, -> { order(rdate: :asc) }, dependent: :destroy
  has_many :timelines, -> { order(no: :desc) }, dependent: :destroy
  
  def age
    Time.new.year - self.birth_year
  end
end

app/controllers/exercise_histories_controller.rb
class ExerciseHistoriesController < ApplicationController

  before_action :set_exercise_history, only: [:show, :edit, :update, :destroy]
  def index
    @exercise_histories = ExerciseHistory.all
  end

  def show
    @user = @exercise_history.day_history.user
    @timeline = @exercise_history.day_history.timeline
  end

  def edit
  end

  def set_exercise_history
    @exercise_history = ExerciseHistory.find(params[:id])
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/choices_helper.rb
module ChoicesHelper
end

app/helpers/episodes_helper.rb
module EpisodesHelper
end

app/helpers/exercise_histories_helper.rb
module ExerciseHistoriesHelper
end

app/helpers/exercises_helper.rb
module ExercisesHelper
end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/steps_helper.rb
module StepsHelper
end

app/views/exercise_histories/_form.html.erb
<%= form_for(@exercise_history, html: { role: "form" }) do |f| %>
  <% if @exercise_history.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@exercise_history.errors.count, "error") %> prohibited this exercise_history from being saved:</h4>

      <ul>
      <% @exercise_history.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/exercise_histories/edit.html.erb
<div class="page-header">
  <h1>Editing exercise_history</h1>
</div>

<%= render 'form' %>


<hr>
<%= link_to exercise_histories_path, class: 'btn btn-default' do %>
  <span class="glyphicon glyphicon-list-alt"></span>
  Back
<% end %>
<%= link_to @exercise_history, class: 'btn btn-default' do %>
  <span class="glyphicon glyphicon-info-sign"></span>
  Show
<% end %>

app/views/exercise_histories/index.html.erb
<div class="page-header">
  <h1>Listing exercise_histories</h1>
</div>

<div class="table-responsive">
  <table class="table table-sm table-hover">
    <thead>
      <tr>
            <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @exercise_histories) do |exercise_history| %>
            <td><%= exercise_history.id %></td>
          <td>
          <%= link_to 'Show', exercise_history %> |
          <%= link_to 'Edit', edit_exercise_history_path(exercise_history) %> |
          <%= link_to 'Destroy', exercise_history, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>

  <%= link_to new_exercise_history_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Exercise history
  <% end %>
  
</div>

app/views/exercise_histories/new.html.erb
<div class="page-header">
  <h1>New exercise_history</h1>
</div>

<%= render 'form' %>

<%= link_to exercise_histories_path, class: 'btn btn-default' do %>
  <span class="glyphicon glyphicon-list-alt"></span>
  Back
<% end %>

app/views/exercise_histories/show.html.erb
<div class="page-header">
  <h1 class="font-weight-bold"><%= @user.name %>님 타임라인</h1>
</div>
<hr class="headerUnderline">

<div class="headSummary">
  <div>
    <span class="greenBadgeHeader">
      <div>
        <%= I18n.t("timeline_type.#{@timeline.timeline_type}") %>
      </div>
    </span>
    <span class="title">
      <%= @timeline.day_history.day_seq %>일차
    </span>
  </div>
  <div>
  <span class="mr-2">
    <i></i>  <%= @timeline.day_history.last_episode_no %> 회기 활동 <%= @timeline.day_history.last_exercise_no %>/<%= @timeline.day_history.total_exercise_no %> 완료 
  </span>
  <span class="mr-2">
    <i></i> 총 <%= @timeline.day_history.duration %>분 소요
  </span>
  <span class="mr-2">
    <i></i> <%= @timeline.rdate.strftime("%Y/%m/%d")=%>
  </span>
  </div>
</div>

<hr class="underHeaderUnderLine">

<div class="subHeadSummary">
  <div>
    <span class="font-weight-bold"><%= @exercise_history.exercise.episode.no %>회기 /</span>
    <span class="font-weight-bold"><%= @exercise_history.exercise.title %></span>
  </div>
  <div>
    <span class="mr-2"><i></i><%= @exercise_history.exercise.time %>분</span>
    <span><i></i><%= @exercise_history.end_at.strftime("%Y/%m/%d %H:%M:%S") %></span>
  </div>
</div>
<hr class="underHeaderUnderLineBelow">
<div class="mt-3">
    <table class="table table table">
      <thead>
        <tr class="text-center">
          <th style="width: 16%"></th>
          <th style="width: 42%">질문</th>
          <th style="width: 42%">답변</th>
        </tr>
      </thead>
      <tbody>
    
        <% @exercise_history.answers.each do |answer|%>
          <tr class= "<%= !answer.question_value ? 'borderless' : nil %>">
            <td><%=answer.question_title%></td>
            <td><%=answer.question_value%></td>
            <td><%=answer.value%></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

<hr class="underHeaderUnderLineBelow">

<div class="footer">
  <div>
    <%= link_to user_timeline_path(@user, @timeline), class: 'btn btn-outline-dark' do %>
      <span> 활동 목록</span>
    <% end %>
  </div>
  <div>
    <%= link_to new_user_timeline_path(@user), class: 'btn btn-primary' do %>
      <span class="glyphicon glyphicon-pencil"></span>
      피드백 작성
    <% end %>
  </div>
</div>