config/routes.rb
Rails.application.routes.draw do
  
  resources :conversations
  get 'home/help'
  use_doorkeeper
  resources :episodes do 
    resources :exercises
      get '/exercise_preview', to: 'exercises#preview'
  end

  get '/episodes_preview', to: 'episodes#preview'
  
  

  resources :choices
  resources :questions do 
    resources :choices
  end

  resources :exercises do 
    get 'up', on: :member
    get 'down', on: :member
    resources :steps 
  end  
  
  resources :steps do
    get 'up', on: :member
    get 'down', on: :member 
    resources :questions
  end
    
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  


  get 'home/index'
  get 'home/help'
  get 'home/privacy'

  resources :users do
      collection do
        get 'group_auth'
        get 'group_assign_counselor'
      end
    
    get 'promoteToCounselor', on: :member
    get 'promoteToNormal', on: :member
    resources :timelines do 
      resources :exercise_histories
    end 
  end
  
  get '/users_auth', to: 'users#auth'
  get '/assign_counselor', to: 'users#assign_counselor'




  resources :timelines
  resources :feedbacks
  resources :conversations
  
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # use_doorkeeper
  mount API::Base => '/'
  mount GrapeSwaggerRails::Engine =>  '/swagger_doc'
  
  root to: "users#index"
end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController
  before_action :set_exercise, only: [:show, :edit, :update, :destroy, :up, :down]
  before_action :set_episode, only: [:index, :create, :new, :preview]
  # GET /exercises
  # GET /exercises.json
  def index
    @exercises = @episode.exercises
  end

  # GET /exercises/1
  # GET /exercises/1.json
  def show
  end

  # GET /exercises/new
  def new
    @exercise = @episode.exercises.new
    @exercise.time = 3
  end

  # GET /exercises/1/edit
  def edit
  end

  # POST /exercises
  # POST /exercises.json
  def create
    @exercise = @episode.exercises.new(exercise_params)
    @exercise.no = (@episode.exercises.maximum('no') || 0) + 1
    respond_to do |format|
      if @exercise.save
        format.html { redirect_to episode_exercises_path(@episode), notice: 'Exercise was successfully created.' }
        format.json { render :show, status: :created, location: @exercise }
      else
        format.html { render :new }
        format.json { render json: @exercise.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /exercises/1
  # PATCH/PUT /exercises/1.json
  def update
    # @episode = @exercises.episode
    respond_to do |format|
      if @exercise.update(exercise_params)
        format.html { redirect_to episode_exercises_path(@episode), notice: 'Exercise was successfully updated.' }
        format.json { render :show, status: :ok, location: @exercise }
      else
        format.html { render :edit }
        format.json { render json: @exercise.errors, status: :unprocessable_entity }
      end
    end
  end

  def up
    if @exercise.no > 1
      Exercise.transaction do 
        @episode.exercises.where('no = ?', @exercise.no - 1).update_all("no = no + 1")
        @exercise.no = @exercise.no - 1
        @exercise.save
      end
    end
    redirect_to episode_exercises_path(@episode)
  end
  
  def down
    if @exercise.no < @episode.exercises.size
      Exercise.transaction do 
        @episode.exercises.where('no = ?', @exercise.no + 1).update_all("no = no - 1")
        @exercise.no = @exercise.no + 1
        @exercise.save
      end
    end
    redirect_to episode_exercises_path(@episode)
  end

  # DELETE /exercises/1
  # DELETE /exercises/1.json
  def destroy
    Exercise.transaction do 
      @episode.exercises.where('no > ?', @exercise.no).update_all("no = no - 1")
      @exercise.destroy
    end
    respond_to do |format|
      format.html { redirect_to episode_exercises_path(@episode), notice: 'Exercise was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def preview
    @exercises = @episode.exercises
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_exercise
      age = 3
      @exercise = Exercise.find(params[:id])
      @episode = @exercise.episode
    end
    def set_episode
      @episode = Episode.find(params[:episode_id])
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def exercise_params
      params.require(:exercise).permit(:no, :title, :time, :episode_id)
    end
end

app/helpers/exercises_helper.rb
module ExercisesHelper
end

app/views/exercises/_form.html.erb
<%= form_for([@episode, @exercise], html: { role: "form" }) do |f| %>
  <% if @exercise.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@exercise.errors.count, "error") %> prohibited this exercise from being saved:</h4>

      <ul>
      <% @exercise.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control", placeholder: '활동 제목' %>
  </div>
  <div class="form-group">
    <%= f.label :time %>
    <%= f.number_field :time, class: "form-control", placeholder: '(분)' %>
  </div>
<%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/exercises/edit.html.erb
<div class="page-header">
  <h1>Editing exercise</h1>
</div>

<%= render 'form' %>
<hr>
<%= link_to episode_exercises_path(@episode), class: 'btn btn-default' do %>
  <span class="glyphicon glyphicon-list-alt"></span>
  Back
<% end %>
<%= link_to @exercise, class: 'btn btn-default' do %>
  <span class="glyphicon glyphicon-info-sign"></span>
  Show
<% end %>

app/views/exercises/index.html.erb
<div class="page-header">
  <h1 class="font-weight-bold">회기 <%=@episode.no%> - <%= @episode.title %></h1>
</div>
<hr class="headerUnderline">
<div class="table-responsive">
  <table class="table table-sm table-hover">
    <thead>
      <tr>
        <th>순서</th>
        <th><%= Exercise.human_attribute_name :title %></th>
        <th><%= Exercise.human_attribute_name :time %></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @exercises) do |exercise| %>
        <td><%= exercise.no %></td>
        <td><%=exercise.title %></td>
        <td><%= exercise.time %></td>
        <td>
          <%= link_to '수정', edit_exercise_path(exercise) %>
        </td>
      <% end %>
    </tbody>
  </table>
  <hr class="footerLine">
  <div class="footer"> 
    <div>
      <%= link_to episodes_path, class: 'btn btn-outline-dark' do %>
        <span> 회기 목록</span>
      <% end %>
    </div>
    <div>
      <%= link_to episode_exercise_preview_path, class: 'btn btn-primary' do %>
        <span></span>
        활동 페이지 미리보기
      <% end %>
    </div>
  </div>
</div>

app/views/exercises/new.html.erb
<div class="page-header">
  <h1>New exercise</h1>
</div>

<%= render 'form' %>

<%= link_to exercises_path, class: 'btn btn-default' do %>
  <span class="glyphicon glyphicon-list-alt"></span>
  Back
<% end %>

app/views/exercises/preview.html.erb
<div class="page-header">
  <h1 class="font-weight-bold">활동 페이지 미리보기</h1>
</div>
  <hr class="headerUnderline">

  <div class="sample-page image-type">
    <div id="exercises_preview_title">
      <%= @episode.title %>
    </div>
    <% @exercises.each do |exercise| %>
      <div class="border border-secondary" id="exercises_preview_content">
        <div><%= exercise.title %></div>
        <i class="fas fa-clock"></i>
        <div><%=exercise.time%>분</div>
      </div>
    <% end %>
  </div>

  <hr class="footerLine">
</div>
<div class="footer"> 
    <div>
      <%= link_to  episode_exercises_path(@episode), class: 'btn btn-outline-dark' do %>
        <span> 활동 목록</span>
      <% end %>
  </div>
</div>

app/views/exercises/show.html.erb
<div class="page-header">
  <h1>Show exercise</h1>
</div>

<dl class="dl-horizontal">
  <dt>No:</dt>
  <dd><%= @exercise.no %></dd>

  <dt>Title:</dt>
  <dd><%= @exercise.title %></dd>

  <dt>Time:</dt>
  <dd><%= @exercise.time %></dd>

  <dt>Episode:</dt>
  <dd><%= @exercise.episode %></dd>

</dl>
<%= link_to exercises_path, class: 'btn btn-default' do %>
  <span class="glyphicon glyphicon-list-alt"></span>
  Back
<% end %>
<%= link_to edit_exercise_path(@exercise), class: 'btn btn-primary' do %>
  <span class="glyphicon glyphicon-pencil"></span>
  Edit
<% end %>